# Get the data

Transform into 10 fold validation, each 6 days long.

In [60]:
import statistics as st
def make(df,med):
    x = []
    df["ATR"] = df["Open"]
    for i,row in df.iterrows():
        x.append(st.mean([row["Open"], row["High"],row["Low"], row["Close"]] ))
        df.at[i,"ATR"] = 0 if len(x) <2 else st.stdev(x)
        if len(x) >med:
            x.pop(0) 
    return df

In [61]:
import yfinance as yf
import pandas as pd
from datetime import date
from datetime import timedelta
# Get the data
datas = []
today = date.today()
for i in range(1,10):
    data = yf.download(tickers="EURUSD=X", interval="5m", start = (today - (timedelta(days=i*6))), end= (today - ((timedelta(days=(i-1)*6)))))
    datas.append(make(data,15))

[*********************100%***********************]  1 of 1 completed
[1.0636883676052094, 1.0636035203933716, 1.0636035203933716, 1.0636035203933716, 1.063490390777588, 1.0634904205799103, 1.063490390777588, 1.0636318027973175, 1.0637449324131012, 1.063490390777588, 1.063490390777588, 1.063490390777588, 1.063490390777588, 1.063490390777588, 1.063490390777588]
[*********************100%***********************]  1 of 1 completed
[1.0550192594528198, 1.0551584362983704, 1.0551306009292603, 1.0551584362983704, 1.0549079179763794, 1.0549914836883545, 1.0547966957092285, 1.0547966957092285, 1.0547689199447632, 1.0551862716674805, 1.0551862716674805, 1.0551862716674805, 1.0551862716674805, 1.0551862716674805, 1.0551862716674805]
[*********************100%***********************]  1 of 1 completed
[1.0696902871131897, 1.06963312625885, 1.0698619484901428, 1.0699478387832642, 1.0698906183242798, 1.0699192583560944, 1.0698047280311584, 1.0697475671768188, 1.06966170668602, 1.0697474479675293, 1.0697474479675293, 1.0697474479675293, 1.0697474479675293, 1.0697474479675293, 1.0697474479675293]
[*********************100%***********************]  1 of 1 completed
[1.0730189979076385, 1.0727887749671936, 1.0727311968803406, 1.0727311968803406, 1.0726736783981323, 1.072558581829071, 1.072817474603653, 1.0726736187934875, 1.072932630777359, 1.072932630777359, 1.072875052690506, 1.0730189681053162, 1.0729613900184631, 1.0733356475830078, 1.0733644366264343]
[*********************100%***********************]  1 of 1 completed
[1.0730477273464203, 1.073105275630951, 1.0731917023658752, 1.073306918144226, 1.0732780992984772, 1.0732204914093018, 1.0730477273464203, 1.0731340646743774, 1.0729902386665344, 1.073105365037918, 1.0732492804527283, 1.0731628835201263, 1.0731917023658752, 1.0732204616069794, 1.0732492804527283]
[*********************100%***********************]  1 of 1 completed
[1.0993239283561707, 1.0992635190486908, 1.0992332994937897, 1.0996261239051819, 1.1000193059444427, 1.1023539304733276, 1.1029919385910034, 1.1023539304733276, 1.1018069386482239, 1.101898044347763, 1.1014732420444489, 1.1015642881393433, 1.101776659488678, 1.1015338599681854, 1.1015035510063171]
[*********************100%***********************]  1 of 1 completed
[1.0896510481834412, 1.0893543362617493, 1.0893245935440063, 1.0895322859287262, 1.0895916521549225, 1.0897104740142822, 1.0897698402404785, 1.0897995233535767, 1.0897994935512543, 1.0897995233535767, 1.0899479985237122, 1.0897401571273804, 1.0898292064666748, 1.089918315410614, 1.0897401571273804]
[*********************100%***********************]  1 of 1 completed
[1.0859532356262207, 1.0861892104148865, 1.0860711932182312, 1.0860711932182312, 1.0860711932182312, 1.0861597061157227, 1.0860711932182312, 1.0859237611293793, 1.0858942866325378, 1.0857763290405273, 1.0857763290405273, 1.0857763290405273, 1.0857763290405273, 1.0857763290405273, 1.0857763290405273]
[*********************100%***********************]  1 of 1 completed
[1.0836291313171387, 1.0836291015148163, 1.0837171971797943, 1.0835703909397125, 1.0835117399692535, 1.0833649635314941, 1.0834236145019531, 1.0834823250770569, 1.0835410356521606, 1.0828369855880737, 1.0828369855880737, 1.0828369855880737, 1.0828369855880737, 1.0828369855880737, 1.0828369855880737]

In [62]:

datas[0].head()

,Open,High,Low,Close,Adj Close,Volume,ATR
Datetime,,,,,,,
2023-02-27 00:00:00+00:00,1.055632,1.055743,1.055298,1.055743,1.055743,0,0.000000
2023-02-27 00:05:00+00:00,1.055298,1.055298,1.054964,1.054964,1.054964,0,0.000335
2023-02-27 00:10:00+00:00,1.054964,1.055520,1.054964,1.055298,1.055298,0,0.000259
2023-02-27 00:15:00+00:00,1.055186,1.055409,1.055186,1.055298,1.055298,0,0.000212
2023-02-27 00:20:00+00:00,1.055186,1.055409,1.055186,1.055298,1.055298,0,0.000184